[package]
name = "chooser"
version = "0.1.0"
authors = ["EnricoMiccoli <EnricoMiccoli@users.noreply.github.com>"]
edition = "2018"

[lib]
name = "chooser"
crate-type = ["cdylib"]

[dependencies]
rand = "0.7"

[dependencies.cpython]
version = "0.5"
features = ["extension-module"]
